Mini-Blog/Controllers/AuthController.cs
using System.Configuration;
using System.Web.Mvc;
using Mini_Blog.Models;
using Mini_Blog.Services;

namespace Mini_Blog.Controllers
{
    public class AuthController : Controller
    {
        private readonly IUserData db;

        public AuthController(IUserData db)
        {
            this.db = db;
        }

        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(FormCollection formCollection)
        {
            var isAttemptSuccess = db.AttemptLogin(formCollection["email"], formCollection["password"]);
            if (!isAttemptSuccess)
            {
                ViewData["Message"] = "Your Credential Doesnt match with our record";
                return View();
            }

            var user = db.Get(formCollection["email"]);
            Session["UserID"] = user.Id;
            if (user.IsAdmin)
            {
                Session["IsAdmin"] = true;
            }

            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public ActionResult Logout()
        {
            Session.Clear();
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public ActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Register(User user, FormCollection formCollection)
        {
            if (formCollection["confirmpassword"] != user.Password)
            {
                ViewData["confirmPasswordErrorMessage"] = "Your Password do not match";
                return View();
            }

            if (!ModelState.IsValid)
            {
                return View();
            }

            var registerStatus = db.Add(user);
            if (registerStatus != "OK")
            {
                ViewData["registerStatus"] = registerStatus;
                return View();
            }

            var newUser = db.Get(user.Id);
            Session["UserID"] = newUser.Id;
            if (newUser.IsAdmin)
            {
                Session["IsAdmin"] = "true";
            }

            return RedirectToAction("Index", "Home");
        }
    }
}

Mini-Blog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/angular-app")
</head>
<body ng-app="app">
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Mini Blog", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                @* <li>@Html.ActionLink("Home", "Index", "Home")</li> *@
                <li>@Html.ActionLink("Blog", "Index", "Blog")</li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                @if (Session["UserID"] == null)
                {
                    <li>@Html.ActionLink("Login", "Login", "Auth")</li>
                    <li>@Html.ActionLink("Register", "Register", "Auth")</li>
                }
                else
                {
                    <li>@Html.ActionLink("Logout", "Logout", "Auth")</li>
                    if (Session["IsAdmin"] != null)
                    {
                        <li>@Html.ActionLink("Dashboard", "Index", "Dashboard")</li>
                    }
                }
            </ul>
        </div>
    </div>
</div>
<div class="container body-content">
    @if (ViewData["Message"] != null)
    {
        <div class="alert alert-danger">
            @ViewData["Message"]
        </div>
    }
    @RenderBody()
    <hr/>
    <footer>
        <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
    </footer>
</div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", required: false)
</body>
</html>