Mini-Blog/Controllers/DashboardController.cs
using System.Web.Mvc;
using Mini_Blog.Services;

namespace Mini_Blog.Controllers
{
    public class DashboardController : Controller
    {
        private IUserData db;

        public DashboardController(IUserData db)
        {
            this.db = db;
        }

        [HttpGet]
        public ActionResult Index()
        {
            if (Session["UserID"] == null || Session["IsAdmin"] != "true")
            {
                return RedirectToAction("Index", "Home");
            }

            var model = db.Get((int)Session["UserID"]);

            return View(model);
        }
    }
}

Mini-Blog/Controllers/PostAngularController.cs
using System.Web.Mvc;

namespace Mini_Blog.Controllers
{
    public class PostAngularController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Edit()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Details()
        {
            return View();
        }
    }
}

Mini-Blog/Views/Dashboard/Index.cshtml
@model Mini_Blog.Models.User
@{
    ViewBag.Title = "Dashboard";
}

<div class="container mt-4">
    <nav class="navbar col-md-2" id="sidebar-wrapper" role="navigation">
        <ul class="nav sidebar-nav">
            <li>
                @Html.ActionLink("Home", "Index", "Dashboard")
            </li>
            <li>
                @Html.ActionLink("Post", "Index", "Post")
            </li>
            <li>
                @Html.ActionLink("Post - Angular Js ver.", "Index", "PostAngular")
            </li>
        </ul>
    </nav>
    <div>
        <h2>Welcome @Model.UserName</h2>
    </div>
</div>